Repository howdyai/botkit, pull requests merged in 2018-10, with the labels that each got.

#1479 Expose wss
  lib/Web.js
Labels: enhancement

#1474 Add try/catch to server message parsing
  lib/Web.js
Labels: bug

#1498 rebrand Webex in readme
  readme.md
Labels: Cisco-related, enhancement
