Repository howdyai/botkit, pull requests merged in 2018-07, with the labels that each got.

#1387 #1386: Additional global parameter that can be set to change the typi…
  lib/Web.js
  package-lock.json
Labels: enhancement

#1358 Add `collectResponse` to CoreBot's public types
  lib/Botkit.d.ts
Labels: enhancement

#1085 Externalize the utterances object
  lib/CoreBot.js
  lib/Utils.js
  lib/utterances.json
Labels: enhancement

#1318 Updating typings for interactive messages
  lib/Botkit.d.ts
Labels: Slack-related, enhancement

#1359 Add missing methods to d.ts
  lib/Botkit.d.ts
Labels: enhancement

#1406 Request Signing with Slack Signing Secret
  docs/readme-slack.md
  lib/CoreBot.js
  lib/SlackBot.js
  package-lock.json
Labels: enhancement

#1421 fix: add return types for TeamsAPI method type definitions
  lib/Botkit.d.ts
Labels: bug

#1431 Update CoreBot.js
  lib/CoreBot.js
Labels: bug
